Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -31,15 +31,17 @@ jobs:
         command: docker load -i workspace/image.tar
     - run:
         command: |
-          result=$(./twistcli images scan --ci --details --address https://157.52.255.14:8083 -u demo -p ${PC_COMPUTE_PASS} nginx:latest | grep -c FAIL)
-          echo "result code: $result"; 
-          if [ $result -eq 0 ];
+          result=$(./twistcli images scan --ci --details --address https://157.52.255.14:8083 -u demo -p ${PC_COMPUTE_PASS} nginx:latest)
+          code=$(echo "$result" |grep FAIL | awk '{print $1}')
+          echo "result: $result"; 
+          echo "code: $code"; 
+          if [[ "$code" -eq 1 || "$code" -eq 2 ]] 
             then 
-              echo "pass code: $result"; 
-              exit 0; 
+              echo "pass code: $code"; 
+              exit 1; 
             else
-              echo "fail code: $result";
-              exit 1;
+              echo "fail code: $code";
+              exit 0;
           fi
     
 workflows:
